#!/usr/bin/env python3
"""Benchmark the L1-L5 pipeline on the seeded repo — latency + accuracy.

Run:  PATH="$PWD/.venv/bin:$PATH" PYTHONPATH=. .venv/bin/python bench/bench_pipeline.py
Writes bench/results/benchmark.json + bench/results/REPORT.md (committed artifacts).
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))
from bench.harness import env_info, gpu_info, timeit, write_report  # noqa: E402

REPO = str(ROOT / "demo" / "seeded_repo")
GT = json.loads((Path(REPO) / "GROUND_TRUTH.json").read_text())
TRUTH = {(f["file"], f["cwe"]) for f in GT["findings"]}
_FP = GT["planted_false_positives"][0]
FP_FILE, FP_LO, FP_HI = _FP["file"], _FP["line"], _FP["line"] + 8


def _prf(pred: set, fp_leak: bool) -> dict:
    tp = len(pred & TRUTH); fp = len(pred - TRUTH) + (1 if fp_leak else 0); fn = len(TRUTH - pred)
    p = tp / (tp + fp) if tp + fp else 0.0
    r = tp / (tp + fn) if tp + fn else 0.0
    return {"P": round(p, 3), "R": round(r, 3),
            "F1": round(2 * p * r / (p + r), 3) if p + r else 0.0, "fp_leak": fp_leak}


def main() -> int:
    from sscai.graph.resolver import RepoGraph
    from sscai.graph.taint import analyze_repo
    from sscai.sast.runner import run_semgrep, run_bandit, scan
    from sscai.sast.normalize import from_semgrep, from_bandit
    from sscai.validation.local_oracle import verify_patch_local

    # ---- latency (median of N) ----
    timings = [
        timeit("L1 graph build (Jedi)", lambda: RepoGraph(REPO).build(), repeats=5),
        timeit("L1 inter-proc taint", lambda: analyze_repo(REPO), repeats=5),
        timeit("L3 semgrep (our rules)", lambda: run_semgrep(REPO), repeats=3),
        timeit("L3 bandit", lambda: run_bandit(REPO), repeats=3),
        timeit("L3 full scan (semgrep+bandit)", lambda: scan(REPO), repeats=3),
    ]

    # ---- L5 oracle (heavy: applies patch + N exploit/test runs) ----
    VULN = ("    query = \"SELECT id, name, email FROM users WHERE name = '%s'\" % username\n"
            "    cur.execute(query)  # << SQLi sink (CWE-89)")
    FIX = "    cur.execute(\"SELECT id, name, email FROM users WHERE name = ?\", (username,))"

    def _patch(repo: Path):
        db = repo / "db.py"; db.write_text(db.read_text().replace(VULN, FIX))

    t_l5 = timeit("L5 dynamic oracle (n=3 runs)",
                  lambda: verify_patch_local(REPO, "exploits/check_sqli.py", _patch, n=3),
                  repeats=1, warmup=0)
    timings.append(t_l5)

    # ---- accuracy (ablation rungs) ----
    sg = [c for c in (from_semgrep(r) for r in run_semgrep(REPO).get("results", []))
          if "/tests/" not in c.path and "/exploits/" not in c.path]
    bd = [c for c in (from_bandit(r) for r in run_bandit(REPO).get("results", []))
          if "/tests/" not in c.path and "/exploits/" not in c.path]
    taint = analyze_repo(REPO)

    def cwe(c): return c.cwe[0].split(":")[0] if c.cwe else ""
    def names(cs): return {(Path(c.path).name, cwe(c)) for c in cs}
    def leak(cs): return any(Path(c.path).name == FP_FILE and FP_LO <= c.line <= FP_HI for c in cs)

    pa = names(sg)
    pb = pa | names(bd)
    pc = pb | {(Path(p.sink.split("::")[0]).name, p.cwe) for p in taint}
    accuracy = {
        "A_semgrep_ce_only": _prf(pa, leak(sg)),
        "B_plus_bandit": _prf(pb, leak(sg + bd)),
        "C_plus_crossfile_taint": _prf(pc, leak(sg + bd)),
        "taint_paths_found": len(taint),
    }

    payload = {"target": "demo/seeded_repo", "env": env_info(), "gpu": gpu_info(),
               "latency": {t.label: t.__dict__ for t in timings}, "accuracy": accuracy}

    # ---- markdown ----
    lines = ["# SovereignSec-AI — Pipeline Benchmark", "",
             f"Target: `demo/seeded_repo` · GPU: {payload['gpu'].get('name')} "
             f"({payload['gpu'].get('vram_total_mib')} MiB, driver {payload['gpu'].get('driver')})",
             f"Python {payload['env']['python']}", "",
             "## Latency (seconds)", "",
             "| stage | median | min | max | runs |", "|---|---|---|---|---|"]
    for t in timings:
        lines.append(f"| {t.label} | {t.median_s} | {t.min_s} | {t.max_s} | {t.runs} |")
    lines += ["", "## Accuracy (ablation vs ground truth)", "",
              "| rung | P | R | F1 | FP-leak |", "|---|---|---|---|---|"]
    for k in ["A_semgrep_ce_only", "B_plus_bandit", "C_plus_crossfile_taint"]:
        a = accuracy[k]
        lines.append(f"| {k} | {a['P']} | {a['R']} | {a['F1']} | {a['fp_leak']} |")
    lines += ["", f"Cross-file taint paths found by L1: **{accuracy['taint_paths_found']}**",
              "", "_Generated by bench/bench_pipeline.py._"]

    write_report(payload, str(ROOT / "bench/results/benchmark.json"),
                 str(ROOT / "bench/results/REPORT.md"), "\n".join(lines))
    print("\n".join(lines))
    print("\nWrote bench/results/benchmark.json + REPORT.md")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
